const express=require('express');
const cors=require('cors');
const bcrypt=require('bcryptjs');
const jwt=require('jsonwebtoken');
const {Pool}=require('pg');
const path=require('path');

const app=express();
app.use(cors());
app.use(express.json());
const pool=new Pool({connectionString:process.env.DATABASE_URL||'postgres://kirathimo:kirathimo@db:5432/kirathimo'});
const JWT_SECRET=process.env.JWT_SECRET||'change-me-in-production';
const ADMIN_EMAIL=process.env.ADMIN_EMAIL||'admin@kirathimo.local';
const ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||'ChangeMe123!';
async function q(sql,p=[]){return (await pool.query(sql,p)).rows;}

async function init(){
 await pool.query(`
 CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'ADMIN',member_id INT REFERENCES members(id),created_at TIMESTAMPTZ DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS members(id SERIAL PRIMARY KEY,name TEXT NOT NULL,phone TEXT,email TEXT,joined_date DATE DEFAULT CURRENT_DATE,active BOOLEAN DEFAULT TRUE,expected_monthly NUMERIC(14,2) DEFAULT 0);
 CREATE TABLE IF NOT EXISTS contributions(id SERIAL PRIMARY KEY,member_id INT REFERENCES members(id),amount NUMERIC(14,2) NOT NULL,contribution_date DATE DEFAULT CURRENT_DATE,month DATE NOT NULL,notes TEXT,units NUMERIC(18,8) DEFAULT 0,unit_price NUMERIC(18,8) DEFAULT 1);
 CREATE TABLE IF NOT EXISTS loans(id SERIAL PRIMARY KEY,member_id INT REFERENCES members(id),principal NUMERIC(14,2) NOT NULL,interest_rate NUMERIC(8,3) DEFAULT 10,status TEXT DEFAULT 'ACTIVE',issued_date DATE DEFAULT CURRENT_DATE,due_date DATE,paid NUMERIC(14,2) DEFAULT 0);
 CREATE TABLE IF NOT EXISTS investments(id SERIAL PRIMARY KEY,name TEXT NOT NULL,type TEXT NOT NULL,quantity NUMERIC(18,6) DEFAULT 0,cost NUMERIC(14,2) DEFAULT 0,current_value NUMERIC(14,2) DEFAULT 0,notes TEXT);
 CREATE TABLE IF NOT EXISTS transactions(id SERIAL PRIMARY KEY,kind TEXT NOT NULL,amount NUMERIC(14,2) NOT NULL,member_id INT REFERENCES members(id),reference TEXT,tx_date DATE DEFAULT CURRENT_DATE,notes TEXT);
 CREATE TABLE IF NOT EXISTS audit_log(id SERIAL PRIMARY KEY,user_id INT REFERENCES users(id),action TEXT NOT NULL,entity TEXT,entity_id INT,details JSONB,created_at TIMESTAMPTZ DEFAULT NOW());
 `);
 await pool.query(`ALTER TABLE contributions ADD COLUMN IF NOT EXISTS units NUMERIC(18,8) DEFAULT 0; ALTER TABLE contributions ADD COLUMN IF NOT EXISTS unit_price NUMERIC(18,8) DEFAULT 1;`);
 await pool.query(`ALTER TABLE members ADD COLUMN IF NOT EXISTS expected_monthly NUMERIC(14,2) DEFAULT 0;`);
 await pool.query(`UPDATE contributions SET units=amount,unit_price=1 WHERE units IS NULL OR units=0`);
 const hash=await bcrypt.hash(ADMIN_PASSWORD,12);
 await pool.query(`INSERT INTO users(email,password_hash,role) VALUES($1,$2,'ADMIN') ON CONFLICT(email) DO NOTHING`,[ADMIN_EMAIL,hash]);
 const [{n}]=await q('SELECT COUNT(*)::int n FROM members');
 if(n===0){
  const m=await q("INSERT INTO members(name,phone,email,expected_monthly) VALUES ('Sample Member A','0700000000','a@example.com',10000),('Sample Member B','0711111111','b@example.com',10000) RETURNING id");
  await pool.query("INSERT INTO contributions(member_id,amount,month,units,unit_price) VALUES ($1,10000,date_trunc('month',CURRENT_DATE),10000,1),($2,15000,date_trunc('month',CURRENT_DATE),15000,1)",[m[0].id,m[1].id]);
  await pool.query("INSERT INTO investments(name,type,quantity,cost,current_value) VALUES ('Kenya Pipeline Company','LISTED_SHARE',100,8500,9200),('Kirathimo MMF','MONEY_MARKET_FUND',1,50000,51200),('Government Bond','BOND',1,100000,103500)");
  await pool.query("INSERT INTO transactions(kind,amount,reference,notes) VALUES ('CONTRIBUTION',25000,'SEED-CONTRIBUTIONS','Demo seed data'),('INVESTMENT_PURCHASE',158500,'SEED-INVESTMENTS','Demo seed data')");
 }
}
function auth(req,res,next){const h=req.headers.authorization||'';const token=h.startsWith('Bearer ')?h.slice(7):null;if(!token)return res.status(401).json({error:'Admin login required'});try{req.user=jwt.verify(token,JWT_SECRET);next()}catch{return res.status(401).json({error:'Invalid or expired login'})}}
async function audit(req,action,entity,id,details={}){if(req.user)await pool.query('INSERT INTO audit_log(user_id,action,entity,entity_id,details) VALUES($1,$2,$3,$4,$5)',[req.user.id,action,entity,id,JSON.stringify(details)]);}
async function nav(){
 const [{investments}]=await q('SELECT COALESCE(SUM(current_value),0)::numeric investments FROM investments');
 const [{loans}]=await q("SELECT COALESCE(SUM(GREATEST(principal-paid,0)),0)::numeric loans FROM loans WHERE status!='PAID'");
 const [{cash}]=await q(`SELECT COALESCE(SUM(CASE WHEN kind IN ('CONTRIBUTION','LOAN_REPAYMENT','INVESTMENT_SALE','INCOME') THEN amount WHEN kind IN ('LOAN_DISBURSEMENT','INVESTMENT_PURCHASE','EXPENSE') THEN -amount ELSE 0 END),0)::numeric cash FROM transactions`);
 const [{units}]=await q('SELECT COALESCE(SUM(units),0)::numeric units FROM contributions');
 const netAssets=+investments + +loans + +cash; const unitPrice=+units?netAssets/+units:1;
 const [{contributions}]=await q('SELECT COALESCE(SUM(amount),0)::numeric contributions FROM contributions');
 const [{gain}]=await q('SELECT COALESCE(SUM(current_value-cost),0)::numeric gain FROM investments');
 return {netAssets,investments:+investments,loansReceivable:+loans,cash:+cash,totalUnits:+units,unitPrice,contributions:+contributions,investmentGain:+gain,asOf:new Date().toISOString()};
}
app.get('/api/health',(r,s)=>s.json({ok:true,group:'Kirathimo Family Investment Group',version:'3.0.0'}));
app.post('/api/login',async(r,s)=>{const {email,password}=r.body||{};const u=(await q('SELECT * FROM users WHERE lower(email)=lower($1)',[email||'']))[0];if(!u||!(await bcrypt.compare(password||'',u.password_hash)))return s.status(401).json({error:'Incorrect email or password'});const token=jwt.sign({id:u.id,email:u.email,role:u.role,member_id:u.member_id},JWT_SECRET,{expiresIn:'12h'});s.json({token,user:{id:u.id,email:u.email,role:u.role,member_id:u.member_id}})});
app.get('/api/nav',async(r,s)=>s.json(await nav()));
app.get('/api/dashboard',async(r,s)=>{const n=await nav();const [{members}]=await q('SELECT COUNT(*)::int members FROM members WHERE active');const [{overdue}]=await q("SELECT COUNT(*)::int overdue FROM loans WHERE status!='PAID' AND due_date IS NOT NULL AND due_date<CURRENT_DATE");const [{arrears}]=await q(`SELECT COALESCE(SUM(GREATEST(expected_monthly - COALESCE(c.month_paid,0),0)),0)::numeric arrears FROM members m LEFT JOIN (SELECT member_id,date_trunc('month',month)::date month,SUM(amount) month_paid FROM contributions GROUP BY member_id,date_trunc('month',month)::date)c ON c.member_id=m.id AND c.month=date_trunc('month',CURRENT_DATE)::date WHERE m.active`);s.json({members:+members,overdueLoans:+overdue,arrears:+arrears,...n})});
app.get('/api/members',async(r,s)=>s.json(await q(`SELECT m.*,COALESCE(SUM(c.amount),0)::numeric contributions,COALESCE(SUM(c.units),0)::numeric units FROM members m LEFT JOIN contributions c ON c.member_id=m.id WHERE m.active GROUP BY m.id ORDER BY m.name`)));
app.get('/api/members/:id',async(r,s)=>{const member=(await q('SELECT * FROM members WHERE id=$1',[r.params.id]))[0];if(!member)return s.status(404).json({error:'Member not found'});const [contrib,loans,tx]=await Promise.all([q('SELECT * FROM contributions WHERE member_id=$1 ORDER BY contribution_date DESC',[r.params.id]),q("SELECT *,GREATEST(principal-paid,0)::numeric outstanding,CASE WHEN due_date IS NOT NULL AND due_date<CURRENT_DATE AND status!='PAID' THEN true ELSE false END overdue FROM loans WHERE member_id=$1 ORDER BY issued_date DESC",[r.params.id]),q('SELECT * FROM transactions WHERE member_id=$1 ORDER BY tx_date DESC,id DESC',[r.params.id])]);const n=await nav();const units=contrib.reduce((a,x)=>a+(+x.units||0),0);const totalUnits=n.totalUnits; s.json({member,contributions:contrib,loans,transactions:tx,units,ownershipPct:totalUnits?units/totalUnits*100:0,ownershipValue:units*n.unitPrice,totalDebt:loans.reduce((a,x)=>a+(+x.outstanding||0),0)});});
app.post('/api/members',auth,async(r,s)=>{const {name,phone,email,expected_monthly}=r.body;if(!name)return s.status(400).json({error:'Name required'});const x=(await q('INSERT INTO members(name,phone,email,expected_monthly) VALUES($1,$2,$3,$4) RETURNING *',[name,phone||'',email||'',+expected_monthly||0]))[0];await audit(r,'CREATE','member',x.id,x);s.status(201).json(x)});
app.patch('/api/members/:id',auth,async(r,s)=>{const {name,phone,email,expected_monthly,active}=r.body;const x=(await q('UPDATE members SET name=COALESCE($1,name),phone=COALESCE($2,phone),email=COALESCE($3,email),expected_monthly=COALESCE($4,expected_monthly),active=COALESCE($5,active) WHERE id=$6 RETURNING *',[name,phone,email,expected_monthly==null?null:+expected_monthly,active,r.params.id]))[0];if(!x)return s.status(404).json({error:'Member not found'});await audit(r,'UPDATE','member',x.id,r.body);s.json(x)});
app.get('/api/contributions',async(r,s)=>s.json(await q('SELECT c.*,m.name member_name FROM contributions c JOIN members m ON m.id=c.member_id ORDER BY contribution_date DESC,id DESC')));
app.post('/api/contributions',auth,async(r,s)=>{const {member_id,amount,month,notes}=r.body;if(!member_id||!amount||+amount<=0)return s.status(400).json({error:'Member and positive amount required'});const n=await nav(),price=n.unitPrice||1,units=+amount/price,client=await pool.connect();try{await client.query('BEGIN');const c=(await client.query('INSERT INTO contributions(member_id,amount,month,notes,units,unit_price) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[member_id,+amount,month||new Date(),notes||'',units,price])).rows[0];await client.query("INSERT INTO transactions(kind,amount,member_id,reference,notes) VALUES('CONTRIBUTION',$1,$2,$3,$4)",[amount,member_id,'CONTR-'+c.id,notes||'']);await client.query('COMMIT');await audit(r,'CREATE','contribution',c.id,c);s.status(201).json(c)}catch(e){await client.query('ROLLBACK');s.status(500).json({error:e.message})}finally{client.release()}});
app.get('/api/arrears',async(r,s)=>s.json(await q(`SELECT m.id,m.name,m.expected_monthly,COALESCE(c.month_paid,0)::numeric month_paid,GREATEST(m.expected_monthly-COALESCE(c.month_paid,0),0)::numeric arrears FROM members m LEFT JOIN (SELECT member_id,SUM(amount) month_paid FROM contributions WHERE month=date_trunc('month',CURRENT_DATE)::date GROUP BY member_id)c ON c.member_id=m.id WHERE m.active ORDER BY arrears DESC,m.name`)));
app.get('/api/loans',async(r,s)=>s.json(await q("SELECT l.*,m.name member_name,GREATEST(l.principal-l.paid,0)::numeric outstanding,CASE WHEN l.due_date IS NOT NULL AND l.due_date<CURRENT_DATE AND l.status!='PAID' THEN 'OVERDUE' ELSE l.status END display_status FROM loans l JOIN members m ON m.id=l.member_id ORDER BY issued_date DESC,id DESC")));
app.post('/api/loans',auth,async(r,s)=>{const {member_id,principal,interest_rate,due_date}=r.body;if(!member_id||!principal||+principal<=0)return s.status(400).json({error:'Member and positive principal required'});const client=await pool.connect();try{await client.query('BEGIN');const x=(await client.query('INSERT INTO loans(member_id,principal,interest_rate,due_date) VALUES($1,$2,$3,$4) RETURNING *',[member_id,+principal,+interest_rate||10,due_date||null])).rows[0];await client.query("INSERT INTO transactions(kind,amount,member_id,reference) VALUES('LOAN_DISBURSEMENT',$1,$2,$3)",[principal,member_id,'LOAN-'+x.id]);await client.query('COMMIT');await audit(r,'CREATE','loan',x.id,x);s.status(201).json(x)}catch(e){await client.query('ROLLBACK');s.status(500).json({error:e.message})}finally{client.release()}});
app.post('/api/loans/:id/repay',auth,async(r,s)=>{const amount=+r.body.amount;if(!amount||amount<=0)return s.status(400).json({error:'Positive amount required'});const old=(await q('SELECT * FROM loans WHERE id=$1',[r.params.id]))[0];if(!old)return s.status(404).json({error:'Loan not found'});const actual=Math.min(amount,Math.max(+old.principal-+old.paid,0));const x=(await q("UPDATE loans SET paid=paid+$1,status=CASE WHEN paid+$1>=principal THEN 'PAID' ELSE 'ACTIVE' END WHERE id=$2 RETURNING *",[actual,r.params.id]))[0];await q("INSERT INTO transactions(kind,amount,member_id,reference) VALUES('LOAN_REPAYMENT',$1,$2,$3)",[actual,x.member_id,'LOAN-'+x.id]);await audit(r,'CREATE','loan_repayment',x.id,{amount:actual});s.json(x)});
app.get('/api/investments',async(r,s)=>s.json(await q('SELECT *, (current_value-cost)::numeric gain FROM investments ORDER BY current_value DESC')));
app.post('/api/investments',auth,async(r,s)=>{const {name,type,quantity,cost,current_value,notes}=r.body;if(!name||!type)return s.status(400).json({error:'Name and type required'});const x=(await q('INSERT INTO investments(name,type,quantity,cost,current_value,notes) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[name,type,+quantity||0,+cost||0,+current_value||0,notes||'']))[0];await q("INSERT INTO transactions(kind,amount,reference,notes) VALUES('INVESTMENT_PURCHASE',$1,$2,$3)",[+cost||0,'INV-'+x.id,notes||'']);await audit(r,'CREATE','investment',x.id,x);s.status(201).json(x)});
app.post('/api/investments/:id/value',auth,async(r,s)=>{const value=+r.body.current_value;if(value<0)return s.status(400).json({error:'Value cannot be negative'});const x=(await q('UPDATE investments SET current_value=$1 WHERE id=$2 RETURNING *',[value,r.params.id]))[0];if(!x)return s.status(404).json({error:'Investment not found'});await audit(r,'UPDATE','investment_value',x.id,{current_value:value});s.json(x)});
app.get('/api/ownership',async(r,s)=>{const n=await nav();return s.json(await q(`SELECT m.id,m.name,COALESCE(SUM(c.units),0)::numeric units,CASE WHEN $1=0 THEN 0 ELSE COALESCE(SUM(c.units),0)/$1*100 END::numeric ownership_pct,COALESCE(SUM(c.units),0)*$2::numeric ownership_value FROM members m LEFT JOIN contributions c ON c.member_id=m.id WHERE m.active GROUP BY m.id ORDER BY ownership_pct DESC`,[n.totalUnits,n.unitPrice]))});
app.get('/api/transactions',async(r,s)=>s.json(await q('SELECT t.*,m.name member_name FROM transactions t LEFT JOIN members m ON m.id=t.member_id ORDER BY tx_date DESC,id DESC')));
app.get('/api/audit',auth,async(r,s)=>s.json(await q('SELECT a.*,u.email FROM audit_log a JOIN users u ON u.id=a.user_id ORDER BY created_at DESC LIMIT 200')));
app.get('/api/export/transactions',auth,async(r,s)=>{const rows=await q('SELECT t.id,t.tx_date,t.kind,m.name member,t.amount,t.reference,t.notes FROM transactions t LEFT JOIN members m ON m.id=t.member_id ORDER BY tx_date,id');const esc=v=>'"'+String(v??'').replace(/"/g,'""')+'"';const csv=[Object.keys(rows[0]||{id:1,tx_date:'',kind:'',member:'',amount:'',reference:'',notes:''}).join(','),...rows.map(x=>Object.values(x).map(esc).join(','))].join('\n');s.setHeader('Content-Type','text/csv');s.setHeader('Content-Disposition','attachment; filename="kirathimo-transactions.csv"');s.send(csv)});
app.use(express.static(path.join(__dirname,'../frontend')));app.get('*',(r,s)=>s.sendFile(path.join(__dirname,'../frontend/index.html')));
init().then(()=>app.listen(process.env.PORT||3000,()=>console.log('Kirathimo v3 running'))).catch(e=>{console.error(e);process.exit(1)});
